reshuffles a couple things around so that dabbing will (hopefully) damage your head again instead of only your arms
vgstation-coders/vgstation13 pull request #33992
Opened 2023-01-10 23:26 UTC by dinnerwoerror

[featureloss] [tweak]

## What this does
We have suffered for 3 long weeks without the ability to brain ourselves at a moments notice, we have been stabbed in the back by the bug "fixers" at #33783, SHADOW NERFING us, and now dabbing targets only your arms rather than your arms and your head, now you cannot dab after 5 dabs because it gibs your arms, you cannot dab without arms, we take the silliness seriously while the coders remove silliness from the game, we are on a FAST TRACK to SOULLESS SHITTOWN and we must change this course before we drive out the TRUE spacemen who keep the HEART of this community alive

but also I don't know if this will actually work so will the downvoters please come out of the woodworks to tell me what I did wrong

## Why it's good
![Capture](https://user-images.githubusercontent.com/120611442/211681908-08cffd21-cbff-4be8-8304-e7a22e48ec54.PNG)

## Changelog

:cl:
 * tweak: reshuffles a couple things around so that dabbing will (hopefully) damage your head again instead of only your arms

2023-01-11 00:55 UTC, pedr69 commented
might as well remove the restrained/unconscious/has_arms checks if it's an actual feature
so doing it is less esoteric and gay

not that my opinion counts much after i've been put into the soyak

2023-01-11 12:26 UTC, tinysaturn commented
> might as well remove the restrained/unconscious/has_arms checks if it's an actual feature so doing it is less esoteric and gay
> 
> not that my opinion counts much after i've been put into the soyak

![627 - SoyBooru](https://user-images.githubusercontent.com/78547984/211805973-1c127683-7cbb-4e78-871f-57695039e14f.png)

2023-01-12 13:34 UTC, Jeremopolis commented
doing god's work

2023-01-12 18:56 UTC, dinnerwoerror commented
> might as well remove the restrained/unconscious/has_arms checks if it's an actual feature so doing it is less esoteric and gay
> 
> not that my opinion counts much after i've been put into the soyak

what's a feature is being prevented from performing certain emotes while restrained or unconscious so you can still chloral syringe the edgy memesters, what's an _actual_ feature is smacking your arms into your forehead a dozen times to create a pool of blood and gore on-demand instead of smacking your arms into eachother like some kind of bygone COVIDiot greeting from years past

2023-01-12 19:59 UTC, Kurfursten requested changes
The changes in this PR don't actually do anything, and you definitely did not test this.

I would help you fix this but I am not sure what exactly you want this PR to do (it seems dabbing isn't hurting the head anymore?). Please state clearly what you intend the PR to in the "what this does" section and move all of the joke text somewhere else. At that point I'll look at the emote code and help you figure out how to do what you want to do.

2023-01-13 01:49 UTC, dinnerwoerror commented
I have been mentally assassinated by facts and logic

Take my place on the line honey nut jeremos

2023-01-13 01:49 UTC, closed without merging

2023-01-13 04:44 UTC, Kurfursten commented
There is no need to close this, I can show you how to fix it if you help me help you.

2023-01-13 04:54 UTC, Exxion commented
![image](https://user-images.githubusercontent.com/9827785/212240440-34471bb7-8e73-43b0-ad65-18f772d435e2.png)
Works On My Machine